"use client";

import Image from 'next/image';
import { useState, useEffect } from 'react';

// Import the image manifest (generated by scripts/generate-or-download-images.sh)
let imageManifest = {};
try {
  imageManifest = require('./imageManifest');
} catch (e) {
  // Manifest not generated yet, fall back to legacy behavior
  console.warn('Image manifest not found, using legacy image selection');
}

/**
 * SharedHero Component
 * 
 * A reusable hero component for landing pages across all iiskills apps.
 * This component provides:
 * - Full-width hero background image
 * - Image selection from manifest (license-free URLs or generated images)
 * - Responsive height settings (520px desktop, smaller on mobile)
 * - Dark overlay for text readability
 * - Positioned content area
 * 
 * Usage:
 *   <SharedHero appName="learn-cricket">
 *     <h1>Your Hero Content</h1>
 *   </SharedHero>
 * 
 * Props:
 * @param {string} appName - The app identifier for image selection (e.g., "learn-cricket", "main")
 * @param {React.ReactNode} children - Content to display in the hero overlay
 * @param {string} className - Additional CSS classes for the hero section
 */

/**
 * Fallback: Shared pool of images for apps without specific hero images
 */
const SHARED_HERO_POOL = [
  'hero1.jpg',
  'hero2.jpg',
  'hero3.jpg'
];

/**
 * Fallback: Cricket-specific hero images pool
 */
const CRICKET_HERO_POOL = [
  'cricket1.jpg',
  'cricket2.jpg'
];

/**
 * Get hero image config for a specific app using manifest or fallback
 * @param {string} appName - The app identifier (e.g., "learn-cricket", "main")
 * @returns {object|null} Image config { src, isRemote, credit } or null for no hero
 */
export function getHeroImageForApp(appName) {
  if (!appName) {
    return { src: `/images/${SHARED_HERO_POOL[0]}`, isRemote: false, credit: null };
  }

  // Try to get from manifest first
  const manifestEntry = imageManifest[appName];
  if (manifestEntry) {
    // Case 1: No image configured
    if (manifestEntry.localPath === null && !manifestEntry.remoteUrl) {
      return null;
    }
    
    // Case 2: Local generated image exists
    if (manifestEntry.localPath && typeof window !== 'undefined') {
      // Check if the local file exists (client-side only)
      return {
        src: manifestEntry.localPath,
        isRemote: false,
        credit: manifestEntry.credit || null,
        isGenerated: manifestEntry.generatedViaGemini || false
      };
    }
    
    // Case 3: Use remote URL (license-free)
    if (manifestEntry.remoteUrl) {
      return {
        src: manifestEntry.remoteUrl,
        isRemote: true,
        credit: manifestEntry.credit || null,
        isGenerated: false
      };
    }
  }

  // Fallback to legacy deterministic mapping
  let legacyImage = null;
  switch (appName) {
    case 'main':
      legacyImage = 'main-hero.jpg';
      break;
    case 'learn-apt':
      legacyImage = 'little-girl.jpg';
      break;
    case 'learn-management':
      legacyImage = 'girl-hero.jpg';
      break;
    case 'learn-cricket':
      legacyImage = CRICKET_HERO_POOL[0];
      break;
    case 'learn-companion':
      return null;
    default:
      const hash = appName.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
      legacyImage = SHARED_HERO_POOL[hash % SHARED_HERO_POOL.length];
  }
  
  return { src: `/images/${legacyImage}`, isRemote: false, credit: null };
}

/**
 * SharedHero Component
 */
export default function SharedHero({ 
  appName, 
  children, 
  className = ''
}) {
  const [heroConfig, setHeroConfig] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Select image on mount to avoid hydration issues
    const config = getHeroImageForApp(appName);
    setHeroConfig(config);
    setIsLoading(false);
  }, [appName]);

  // If no hero image (e.g., learn-companion), return null
  if (!isLoading && heroConfig === null) {
    return null;
  }

  // Don't render until we have config to avoid hydration mismatch
  if (isLoading || !heroConfig) {
    return null;
  }

  return (
    <section 
      className={`relative w-full overflow-hidden ${className}`}
      style={{ 
        height: '520px',
        minHeight: '400px'
      }}
    >
      {/* Full-size background image */}
      {heroConfig.src && (
        <div className="absolute inset-0 z-0">
          {heroConfig.isRemote ? (
            // Remote image (license-free URL) - use img tag for external URLs
            <img
              src={heroConfig.src}
              alt="Hero background"
              className="w-full h-full object-cover"
              style={{ objectPosition: '50% 30%' }}
            />
          ) : (
            // Local image - use Next.js Image component
            <Image
              src={heroConfig.src}
              alt="Hero background"
              fill
              className="object-cover"
              style={{ objectPosition: '50% 30%' }}
              sizes="100vw"
              priority
            />
          )}
        </div>
      )}

      {/* Overlay for better text readability */}
      <div className="absolute inset-0 bg-black/40 z-10" aria-hidden="true"></div>

      {/* Content container - positioned absolutely so overlay content can be placed */}
      <div className="relative z-20 h-full flex items-end pb-12 md:pb-16 lg:pb-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full">
          {children}
          
          {/* Image credit if available */}
          {heroConfig.credit && (
            <div className="mt-4 text-xs text-white/60">
              Photo by <a 
                href={heroConfig.credit.sourceUrl} 
                target="_blank" 
                rel="noopener noreferrer"
                className="underline hover:text-white/80"
              >
                {heroConfig.credit.sourceName}
              </a>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
