nodeLinker: node-modules

# Enable workspace protocol for internal dependencies
enableGlobalCache: true

# Prefer deduplication
enableImmutableInstalls: false

# Better error messages
enableInlineBuilds: false
