/**
 * PM2 Ecosystem Configuration File for iiskills-cloud
 * 
 * Auto-generated configuration for all Next.js applications in the repository.
 * Each app is configured to run independently with its own port and logs.
 * 
 * This file was automatically generated by generate-ecosystem.js
 * DO NOT EDIT MANUALLY - regenerate using: node generate-ecosystem.js
 * 
 * All apps use Next.js and their package.json 'start' scripts, which include
 * port specifications where defined.
 * 
 * Usage:
 *   pm2 start ecosystem.config.js          # Start all apps
 *   pm2 start ecosystem.config.js --only <app-name>  # Start specific app
 *   pm2 stop all                           # Stop all apps
 *   pm2 restart all                        # Restart all apps
 *   pm2 logs                               # View logs
 *   pm2 monit                              # Monitor processes
 *   pm2 save                               # Save current process list
 *   pm2 startup                            # Enable PM2 to start on system boot
 * 
 * Prerequisites:
 *   1. Run 'npm install' in root and each subdirectory before starting
 *   2. Run 'npm run build' in root and each subdirectory to build production bundles
 *   3. Ensure all environment variables are configured (.env files)
 * 
 * Cross-platform compatible with Windows and Unix-like systems.
 */

const path = require('path');

module.exports = {
  apps: [
    // Learn AI - Comprehensive AI Course Platform
    {
      name: 'iiskills-learn-ai',
      cwd: path.join(__dirname, 'apps/learn-ai'),
      script: 'npm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        // PORT 3024 is specified in package.json start script
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: path.join(__dirname, 'logs', 'learn-ai-error.log'),
      out_file: path.join(__dirname, 'logs', 'learn-ai-out.log'),
      log_file: path.join(__dirname, 'logs', 'learn-ai-combined.log'),
      time: true
    },
    
    // Learn Apt - Free Aptitude Testing Platform
    {
      name: 'iiskills-learn-apt',
      cwd: path.join(__dirname, 'apps/learn-apt'),
      script: 'npm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        // PORT 3002 is specified in package.json start script
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: path.join(__dirname, 'logs', 'learn-apt-error.log'),
      out_file: path.join(__dirname, 'logs', 'learn-apt-out.log'),
      log_file: path.join(__dirname, 'logs', 'learn-apt-combined.log'),
      time: true
    },
    
    // Learn Companion - Your AI Life Advisor
    {
      name: 'iiskills-learn-companion',
      cwd: path.join(__dirname, 'apps/learn-companion'),
      script: 'npm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        // PORT 3023 is specified in package.json start script
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: path.join(__dirname, 'logs', 'learn-companion-error.log'),
      out_file: path.join(__dirname, 'logs', 'learn-companion-out.log'),
      log_file: path.join(__dirname, 'logs', 'learn-companion-combined.log'),
      time: true
    },
    
    // main module
    {
      name: 'iiskills-main',
      cwd: path.join(__dirname, 'apps/main'),
      script: 'npm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        // PORT 3000 is specified in package.json start script
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: path.join(__dirname, 'logs', 'main-error.log'),
      out_file: path.join(__dirname, 'logs', 'main-out.log'),
      log_file: path.join(__dirname, 'logs', 'main-combined.log'),
      time: true
    }
  ]
}
