/**
 * Next.js Edge Middleware — learn-management
 *
 * Admin bypass (infallible rule): reads the Supabase auth cookie, decodes the
 * JWT to extract the user's email and is_admin flag, then calls hasAccess().
 * If hasAccess() returns true the request is tagged with x-admin-access and
 * allowed through immediately — no payment redirect will fire.
 *
 * Fallback: if the URL contains ?admin_access=true the same bypass is applied
 * without requiring a valid session (admin preview links from apps/main).

 * Calls checkUserAccess BEFORE any page content is rendered, eliminating the
 * client-side "paywall flash" that occurred when access control ran in the
 * browser after the page had already started loading.

 *
 * Access priority (handled by checkUserAccess):
 *  1. Admin preview query param (?admin_access=true) — immediate pass-through.
 *  2. Admin / product-owner master key (is_admin or philipda@gmail.com) — exit early.
 *  3. Active paid entitlement in Supabase JWT app_metadata — allow.
 *  4. No access — redirect to /enrol on the main site.
 *
 * The landing page ("/") is always public to preserve the marketing page.
 */
import { NextResponse } from "next/server";

import { hasAccess, parseUserFromCookies, checkUserAccess } from "@iiskills/access-control";

import { createServerClient } from "@supabase/ssr";

/** App identifier for this sub-app. */
const APP_ID = "learn-management";


/** Base URL of the main site — used to build the absolute redirect URL. */
const MAIN_APP_URL = process.env.NEXT_PUBLIC_MAIN_APP_URL || "https://iiskills.cloud";




export async function proxy(request) {
  const { pathname, searchParams } = request.nextUrl;

  // ── 1. Admin preview pass-through ─────────────────────────────────────────
  // Links generated by apps/main admin panel include ?admin_access=true.
  // Tag the response and let it through immediately — no payment redirect.
  if (searchParams.get("admin_access") === "true") {

    const response = NextResponse.next();
    response.headers.set("x-admin-access", "1");
    return response;
  }

  // ── 2. Public landing page ─────────────────────────────────────────────────
  // The root "/" is the public marketing page — always accessible.
  if (pathname === "/") {
    return NextResponse.next();
  }

  // ── 3. Session-aware access check ─────────────────────────────────────────
  // Skip the check when Supabase credentials are not configured (CI builds).
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseAnonKey) {
    return NextResponse.next();
  }

  // Refresh the session cookie if it has expired, then read the user.
  const response = NextResponse.next({ request });

  const supabase = createServerClient(supabaseUrl, supabaseAnonKey, {
    cookies: {
      getAll() {
        return request.cookies.getAll();
      },
      setAll(cookiesToSet) {
        // Propagate any refreshed session cookies to the outgoing response.
        cookiesToSet.forEach(({ name, value, options }) =>
          response.cookies.set(name, value, options)
        );
      },
    },
  });

  // getSession() reads from the cookie without a network round-trip.
  // The JWT is signed by Supabase so the claims (is_admin, app_entitlements)
  // can be trusted here without an additional server verification call.
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const supabaseUser = session?.user ?? null;

  // Map Supabase user -> AccessUser shape expected by checkUserAccess.
  // is_admin is stored in app_metadata (set via Supabase admin API / service role).
  // The user_metadata fallback handles legacy accounts. app_entitlements are synced
  // to app_metadata by grantAppAccess() in packages/access-control/dbAccessManager.js.
  const accessUser = supabaseUser
    ? {
        is_admin:
          supabaseUser.app_metadata?.is_admin ?? supabaseUser.user_metadata?.is_admin ?? false,
        email: supabaseUser.email,
        app_entitlements: supabaseUser.app_metadata?.app_entitlements ?? [],
      }
    : null;

  // ── 4. Master-key exit — fires BEFORE any payment/entitlement check ────────
  const result = checkUserAccess(accessUser, APP_ID);

  if (!result.allowed) {
    // Redirect to /enrol on the main site (absolute URL required).
    const enrollUrl = new URL(result.redirectTo, MAIN_APP_URL);
    return NextResponse.redirect(enrollUrl);
  }

  return response;
}

export const config = {
  // Exclude static assets; the root "/" is handled explicitly above.
  matcher: ["/((?!_next/static|_next/image|favicon\\.ico|images/).*)"],
};
