#!/usr/bin/env bash

# Helper script to temporarily disable authentication
# This script provides instructions for setting environment variables
# DO NOT store secrets in this script

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Temporary Authentication Disable - Setup Instructions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  SECURITY WARNING:"
echo "This will disable ALL authentication and make ALL content public!"
echo "Only use for temporary debugging/maintenance."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 1: Set environment variables in your current shell"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands in your terminal:"
echo ""
echo "  export DISABLE_AUTH=true"
echo "  export NEXT_PUBLIC_DISABLE_AUTH=true"
echo ""
echo "Then rebuild and restart the application:"
echo ""
echo "  npm run build"
echo "  npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 2: Add to .env.local file (persists across terminal sessions)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Add these lines to your .env.local file:"
echo ""
echo "  DISABLE_AUTH=true"
echo "  NEXT_PUBLIC_DISABLE_AUTH=true"
echo ""
echo "Then rebuild and restart the application:"
echo ""
echo "  npm run build"
echo "  npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "TO REVERT (Re-enable authentication):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If you used shell exports:"
echo "  unset DISABLE_AUTH"
echo "  unset NEXT_PUBLIC_DISABLE_AUTH"
echo "  npm run build"
echo "  npm run dev"
echo ""
echo "If you used .env.local:"
echo "  # Remove or comment out the DISABLE_AUTH lines in .env.local"
echo "  npm run build"
echo "  npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "For more information, see: docs/DISABLE_AUTH_README.md"
echo ""
