import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import { createClient } from '@supabase/supabase-js';

/**
 * ShareButton Component - Client-side only
 */
function ShareButton({ platform, title, className }) {
  const handleShare = () => {
    if (typeof window === 'undefined') return;
    
    const url = window.location.href;
    const shareUrl = platform === 'twitter'
      ? `https://twitter.com/intent/tweet?text=${encodeURIComponent(title)}&url=${encodeURIComponent(url)}`
      : `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`;
    
    window.open(shareUrl, '_blank', 'noopener,noreferrer');
  };

  const label = platform === 'twitter' ? '🐦 Share on Twitter' : '💼 Share on LinkedIn';

  return (
    <button onClick={handleShare} className={className}>
      {label}
    </button>
  );
}

/**
 * Basic HTML sanitization
 * Only allows safe HTML tags from our newsletter template
 */
function sanitizeHTML(html) {
  // The HTML is generated by our own system, not user input
  // This is a basic sanity check for safety
  if (!html || typeof html !== 'string') {
    return '';
  }
  
  // Remove any script tags as extra safety
  return html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
}

/**
 * Individual Newsletter View Page
 * 
 * Display a single newsletter edition in full
 */

export default function ViewNewsletter({ newsletter, error }) {
  const [downloadingPDF, setDownloadingPDF] = useState(false);

  const handleDownloadPDF = async () => {
    setDownloadingPDF(true);
    
    try {
      // Dynamically import jsPDF
      const { jsPDF } = await import('jspdf');
      const html2canvas = (await import('html2canvas')).default;
      
      // Get the newsletter content
      const element = document.querySelector('.newsletter-content');
      
      if (!element) {
        alert('Newsletter content not found');
        return;
      }

      // Create canvas from HTML
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false
      });
      
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });
      
      const imgWidth = 210; // A4 width in mm
      const pageHeight = 297; // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;
      
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
      
      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }
      
      // Download the PDF
      const filename = `skilling-newsletter-${newsletter.edition_number}.pdf`;
      pdf.save(filename);
      
    } catch (error) {
      console.error('PDF generation error:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setDownloadingPDF(false);
    }
  };

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4">
        <div className="bg-white rounded-lg shadow-lg p-8 max-w-md text-center">
          <h1 className="text-2xl font-bold text-gray-800 mb-4">⚠️ Error</h1>
          <p className="text-gray-600 mb-6">{error}</p>
          <Link href="/newsletter/archive">
            <a className="inline-block bg-purple-600 text-white px-6 py-3 rounded-full font-semibold hover:bg-purple-700 transition">
              ← Back to Archive
            </a>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>{newsletter.title} - Skilling Newsletter</title>
        <meta name="description" content={newsletter.intro_text} />
        <meta property="og:title" content={newsletter.title} />
        <meta property="og:description" content={newsletter.intro_text} />
        <meta property="og:type" content="article" />
      </Head>

      <div className="min-h-screen bg-gray-50">
        {/* Navigation */}
        <div className="bg-white border-b shadow-sm">
          <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
            <Link href="/newsletter/archive">
              <a className="text-purple-600 hover:text-purple-700 font-semibold">
                ← All Newsletters
              </a>
            </Link>
            <div className="flex gap-4">
              <Link href="/newsletter">
                <a className="text-gray-600 hover:text-gray-800">
                  Subscribe
                </a>
              </Link>
              <button
                onClick={handleDownloadPDF}
                disabled={downloadingPDF}
                className="text-gray-600 hover:text-gray-800 disabled:opacity-50"
                title="Download as PDF"
              >
                {downloadingPDF ? '⏳ Generating...' : '📥 PDF'}
              </button>
              <button
                onClick={() => window.print()}
                className="text-gray-600 hover:text-gray-800"
              >
                🖨️ Print
              </button>
            </div>
          </div>
        </div>

        {/* Newsletter Content */}
        <div className="max-w-4xl mx-auto px-4 py-12">
          {/* Edition Badge */}
          <div className="text-center mb-6">
            <span className="inline-block bg-purple-100 text-purple-700 px-4 py-2 rounded-full text-sm font-semibold">
              Edition #{newsletter.edition_number}
            </span>
          </div>

          {/* Render HTML Content - sanitized during generation */}
          <div 
            className="newsletter-content bg-white rounded-lg shadow-lg overflow-hidden"
            dangerouslySetInnerHTML={{ 
              __html: sanitizeHTML(newsletter.web_content || newsletter.html_content) 
            }}
          />

          {/* Share & Actions */}
          <div className="mt-8 bg-white rounded-lg shadow-sm p-6">
            <h3 className="text-lg font-bold text-gray-800 mb-4 text-center">
              Share this newsletter 📤
            </h3>
            <div className="flex flex-wrap gap-3 justify-center">
              <button
                onClick={() => {
                  if (typeof window !== 'undefined') {
                    const url = window.location.href;
                    navigator.clipboard.writeText(url);
                    alert('Link copied to clipboard! 📋');
                  }
                }}
                className="bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-full font-semibold transition"
              >
                📋 Copy Link
              </button>
              <ShareButton 
                platform="twitter" 
                title={newsletter.title}
                className="bg-blue-400 hover:bg-blue-500 text-white px-4 py-2 rounded-full font-semibold transition"
              />
              <ShareButton 
                platform="linkedin"
                title={newsletter.title}
                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-full font-semibold transition"
              />
            </div>
          </div>

          {/* CTA */}
          <div className="mt-8 text-center">
            <Link href="/newsletter">
              <a className="inline-block bg-gradient-to-r from-purple-600 to-blue-600 text-white px-8 py-4 rounded-full font-bold text-lg hover:shadow-lg transform hover:-translate-y-1 transition">
                Subscribe to Skilling Newsletter 🚀
              </a>
            </Link>
          </div>
        </div>
      </div>

      <style jsx global>{`
        .newsletter-content {
          /* Ensure content renders well */
        }
        
        @media print {
          .newsletter-content {
            box-shadow: none;
          }
        }
      `}</style>
    </>
  );
}

/**
 * Server-side data fetching
 */
export async function getServerSideProps({ params }) {
  try {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    );

    const { data, error } = await supabase
      .from('newsletter_editions')
      .select('*')
      .eq('id', params.id)
      .single();

    if (error || !data) {
      return {
        props: {
          newsletter: null,
          error: 'Newsletter not found'
        }
      };
    }

    // Only show sent newsletters to public
    if (data.status !== 'sent') {
      return {
        props: {
          newsletter: null,
          error: 'This newsletter has not been published yet'
        }
      };
    }

    return {
      props: {
        newsletter: data,
        error: null
      }
    };

  } catch (error) {
    console.error('Server error:', error);
    return {
      props: {
        newsletter: null,
        error: 'An unexpected error occurred'
      }
    };
  }
}
